worker_processes auto;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    keepalive_timeout 65;

    upstream django_backend {
        server django_web:8000;
    }

    upstream flask_payments_backend {
        server flask_microservice:5000;
    }

    log_format routed '$remote_addr - [$time_local] "$request" '
                     '$status routed_to=$upstream_addr';
    access_log /var/log/nginx/access.log routed;

    server {
        listen 80;
        server_name _;

        # --- Microservicio Flask (nuevo): Strangler captura /api/v2/payments/ ---
        location /api/v2/payments/ {
            proxy_pass         http://flask_payments_backend;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_read_timeout 10s;
        }

        # --- Monolito Django (legacy): API v1 explícita ---
        location /api/v1/ {
            proxy_pass         http://django_backend;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        # --- Fallback: cualquier otra ruta va al monolito Django ---
        # Incluye /api/resources/, /api/reservations/, /admin/, /
        location / {
            proxy_pass         http://django_backend;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}
